### PR TITLE
Fix top

### LINKED ISSUE #70: top pkg issues
I have some problems with top pkg that needs to be solved for https://github.com/cloudradar-monitoring/cagent/pull/69 to be merged

1. Need to add lowercase-naming json struct tags for `ProcessInfo` struct. Any reason you renamed process `Name` into `Identifier`? This could probably confuse both devs & users.

2. I got a lot of logs like this on Linux. I didn't dig  why this procs not exist (maybe very short-lived) but probably need to omit them
image

3. I made a sorting of `GetProcesses()` on my side, but it feels like it should be done on `top` side. The same way it is done in the `top` utility by default.

### PR DESCRIPTION
**Pull request by soupdiver**
Fixes #70 

Should be merged before #69

### CODE REVIEW

File: handler.go [hunk 1]
```diff
@@ -310,7 +310,22 @@ func (ca *Cagent) RunOnce(outputFile *os.File) error {
 	return ca.ReportMeasurements(measurements, outputFile)
 }
 
-func (ca *Cagent) Run(outputFile *os.File, interrupt chan struct{}) {
+func (ca *Cagent) Run(outputFile *os.File, interrupt chan struct{}, cfg *Config) {
+	// Start process utilisation monitoringi in the background
```
Comment (golangcibot) [inline handler.go]: `utilisation` is a misspelling of `utilization` (from `misspell`)

File: config.go [hunk 2]
```diff
@@ -66,7 +66,16 @@ type Config struct {
 
 	VirtualMachinesStat []string `toml:"virtual_machines_stat" comment:"default ['hyper-v'], available options 'hyper-v'"`
 
-	HardwareInventory bool `toml:"hardware_inventory" comment:"default true"`
+	HardwareInventory      bool                   `toml:"hardware_inventory" comment:"default true"`
+	CPUUtilisationAnalysis CPUUtilisationAnalysis `toml:"cpu_utilisation_analysis"`
+}
+
+type CPUUtilisationAnalysis struct {
```
Comment (requilence) [inline config.go]: Did you intentionally put here the struct from my PR?

Comment (soupdiver) [reply config.go]: The decision was made later to move the detection logic to `cpuWatcher`. I had already added this feature to `Top`.
Wasn't sure about the other PR and therefor left this here for now.
I guess I can remove this struct then?

Comment (requilence) [reply config.go]: Ah, got it. Yes, I think so.. I thought that it can be useful to have the analyzer as a separate pkg. So it could be possible attach more pkg like `top` there later

**Comment by requilence** [comment]
Should also remove from `config_test.go` or lets merge and then fix tests after #69?

**Comment by soupdiver** [comment]
addressed issues @requilence
